require "basic_support/version"

require "basic_support/core_ext/class_exists"
require "basic_support/core_ext/to_boolean"
require "basic_support/core_ext/to_integer"
require "basic_support/core_ext/to_array"
require "basic_support/core_ext/is_integer"
require "basic_support/core_ext/max_words"
require "basic_support/core_ext/map_to_hash"
require "basic_support/core_ext/halved"
